package es.developer.projectwar.utils;

public enum UpdateInput {
	POSITION_CHANGED,
	UNIT_UNSELECTED,
	UNIT_SELECTED,
	COMMANDS_UPDATED,
	PLAYER_CHANGED,
	DAY_CHANGED,
	UNIT_ON_RANGE,
	STATE_UPDATED,
	UNIT_TARGETED;
}
